AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Alexa Skill - Heidelburg Catechism
Resources:
  alexaskillheidelburgcatechism:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: developer-alexa-heidelburg-catechism
      Handler: index.handler
      Runtime: nodejs6.10
      Description: Alexa Skill - Heidelburg Catechism
      MemorySize: 128
      Timeout: 7
      Role: >-
        arn:aws:iam::738265248082:role/developer-role-lambda-execute
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
