version: 0.2
phases:
  install:
    commands:
      - npm install alexa-sdk
      - aws cloudformation package --template-file ashc-template.yaml --s3-bucket marlhammer-lambda-build --output-template-file ashc.yaml
artifacts:
  type: zip
  files:
    - ashc.yaml